### ISSUE TITLE
환경설정

### ISSUE THREAD

**Issue by sang-eun** [connect-foundation/2019-17#102]
### backend 
- [x] graphql-yoga
- [x] typescript
- [ ] graphdb or mysql
- [ ] express

### front
- [x] react
- [x] apollo-client
- [x] typescript

### 기타
- [ ] 테스트

**Comment by kyujonglee** [comment]
- merge-graphql-schemas, grqphql-tools를 이용하여 resolvers와 typeDefs를 합쳐 schema를 만듬
- merge-graphql-schemas: fileLoader, mergeResolvers, mergeTypes
- graphql-tools: makeExecutableSchema
- graphql-yoga : GraphQLSchema 

참고 사이트
https://github.com/prisma-labs/graphql-yoga
https://github.com/Urigo/merge-graphql-schemas
