### ISSUE TITLE
Bug: 타임존 설정 버그

### ISSUE THREAD

**Issue by ImuruKevol** [connect-foundation/2019-17#157]
타임존이 기본 타임존으로 되어있어 +0:00인 것 같습니다.
한국 시간으로 +9:00를 해야할 것 같습니다.

**Comment by WooYeonSeo** [comment]
타임존 설정 변경하고, 한글로포맷 맞췄습니다. 이번주 금요일 릴리즈 때 확인 부탁드립니다~
