### ISSUE TITLE
Bug: 친구 검색시 특문 검색시 오류

### ISSUE THREAD

**Issue by ImuruKevol** [connect-foundation/2019-17#160]
친구를 검색할 때 특문을 검색하면 오류가 나거나 모든 유저가 뜹니다.

&npsp;
&
*
이런 문자들이 전부 제대로 처리가 안되는 것 같습니다.

**Comment by sang-eun** [comment]
e6f66758ea60082126edddc87a360a3df418f235

수정하였습니다
