### ISSUE TITLE
bug: 알림 온 피드를 누르면 검정색 화면이 뜹니다.

### ISSUE THREAD

**Issue by munsulim** [connect-foundation/2019-17#195]
실행환경: 우분투
상황: 알림이 와있고 해당 알림을 누르면 검정색 화면이 뜹니다.

**Comment by WooYeonSeo** [comment]
https://github.com/connect-foundation/2019-17/commit/d1fe9d24874c001dd2f05f60c522156b3188db9d 
쿼리에서 댓글 알림 정보를 연결하는데 발생했던 문제로, 쿼리 수정으로 해결했습니다~
이번주 금요일에 같이 묶어서 릴리즈 할게요.
