### ISSUE TITLE
Bug: 알수도 있는 친구 중복 데이터

### ISSUE THREAD

**Issue by dimsssss** [connect-foundation/2019-17#196]
![bug-boost](https://user-images.githubusercontent.com/24388846/70772797-021f9180-1db9-11ea-8b8d-f535ae563271.png)
알수도 있는 친구 추천 데이터가 중복으로 떴어요

**Comment by sang-eun** [comment]
dc147049a914041ca6f664280a1ae13dddfe57d8

수정하였습니다
