### ISSUE TITLE
Bug: 알림창에서 아무것도 출력안되는 경우 발견

### ISSUE THREAD

**Issue by BuildTheTruth** [connect-foundation/2019-17#200]
환경: Window10, Chrome

삭제된 피드인지는 잘 모르겠는데 몇몇 알림을 눌렀을 때 해당 피드가 뜨지 않는 문제가 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/33617083/70773001-81ad6080-1db9-11ea-9359-cb5c0ab6f7f3.png)

**Comment by WooYeonSeo** [comment]
쿼리에서 댓글 알림 정보를 연결하는데 발생했던 문제로, 쿼리 수정으로 해결했습니다~
이번주 금요일에 같이 묶어서 릴리즈 할게요.
