### ISSUE TITLE
무한스크롤

### ISSUE THREAD

**Issue by beingPracticer** [connect-foundation/2019-17#32]

**Comment by WooYeonSeo** [comment]
- 만약 새로운 데이터가 새로 막 생기면 같은 데이터를 또 조회해 올 수 있음 이를 개선하기 위해서 cursor based pagination이 필요
- offset 갯수에 대해서 도 생각이 필요함
- 맨 마지막 페이지에 계속 있으면 계속 데이터를 요청함
- useMemo에서 fetching 하는 바람에 계속 데이터를 중복으로 들고오는 이슈가 발생했었지만 updateQuery 의 prev에서 이전 데이터를 계속 가지고 있다는 것을 알게 되고 수정함
